### PR TITLE
Buffer writes before chunks are written to connection

### LINKED ISSUE #71: Undesired small chunks when writing buffered chunked body
The current behavior when writing a chunked body with `into_buffered()` is currently not as intended as the buffer seems to be on the wrong side of the chunked writer.

Currently many small chunks are encoded and written to the buffer. Instead of the small body writes should somehow be buffered _before_ the `ChunkedBodyWriter` such that the buffered content is written in a large chunk.

What I am seeing right now is a request body with waaay to many chunks of only a few bytes which corresponds to each write to the body. Instead I want the small writes to be buffered and only when the buffer is full/flushed should the chunk be written.

cc @bugadani

### PR DESCRIPTION
**Pull request by rmja**
This commit:
* Moves the responsibility for writing the request body from `Request` to `HttpConnection`.
* Uses the buffer provided when calling `into_buffered()` to buffer writes before they are passed on to the `ChunkedBufferWriter`

This fixes #71

### CODE REVIEW

**Comment by rmja** [comment]
I could use some help making this better.
The problem is now that there are multiple connection flushes during the writing of a request which is quite annoying.

I feel like it somehow should be possible to buffer internally in in the chunked writer in a way such that the chunks gets as large as possible up to the max buffer size.

Any help is greatly appreciated.

**Comment by rmja** [comment]
I have now added a `BufferedChunkedBodyWriter` which now has the responsibility of both buffer and chunk. It will probably need some tests.

**Comment by rmja** [comment]
This is now ready for review. Let me know what you think.

File: src/body_writer.rs [hunk 1]
```diff
@@ -0,0 +1,349 @@
...
+    async fn flush(&mut self) -> Result<(), Self::Error> {
+        if self.header_pos > 0 {
+            self.finish_current_chunk();
+            self.emit_finished_chunk().await.map_err(|e| e.kind())?;
+        }
+        self.conn.flush().await.map_err(|e| e.kind())
+    }
+}
+
+const fn get_hex_chars(number: usize) -> u32 {
```
Comment (bugadani) [inline src/body_writer.rs:237]: It's not at all important but it's not clear at a glance what the purpose of this function is. The name hints at returning characters, but the return type is `u32` which is neither typical of characters, nor of counts, really (it's immediately cast to `usize` anyway)

File: src/body_writer.rs [hunk 2]
```diff
@@ -0,0 +1,349 @@
...
+    if number == 0 {
+        1
+    } else {
+        (usize::BITS - number.leading_zeros()).div_ceil(4)
+    }
+}
+
+const fn get_max_chunk_header_size(buffer_size: usize) -> usize {
+    if buffer_size >= NEWLINE.len() + NEWLINE.len() {
```
Comment (bugadani) [inline src/body_writer.rs:246]: Do you have something against `2*`? :)

Also this function would look much simpler by using `checked_sub()`

File: src/body_writer.rs [hunk 3]
```diff
@@ -0,0 +1,349 @@
...
+        get_hex_chars(buffer_size - NEWLINE.len() - NEWLINE.len()) as usize + NEWLINE.len()
+    } else {
+        // Not enough space in buffer to fit a header + footer
+        0
+    }
+}
+
+fn write_chunked_header(buf: &mut [u8], chunk_len: usize) -> usize {
+    let mut hex = [0; 2 * size_of::<usize>()];
```
Comment (bugadani) [inline src/body_writer.rs:255]: This seems to be incorrect when `chunk_len == 0`. In this case, the function would not print a 0 chunk size, just a newline. Why is that not a problem?

**Review by bugadani — COMMENTED** [review]
Looks mostly OK to me, although I wasn't particularly thorough.

File: src/body_writer.rs (hunk 3 above)
Comment (rmja) [reply src/body_writer.rs:258]: Good catch - it is not a problem because the zero chunk is written using a pre-defined `const EMPTY_CHUNK: &[u8; 5] = b"0\r\n\r\n";` - but you are right - this function should work for `chunk_len == 0` for sanity

File: src/body_writer.rs (hunk 2 above)
Comment (rmja) [reply src/body_writer.rs]: I guess I do :-D No of cause not! I have aligned, thanks!

File: src/body_writer.rs (hunk 1 above)
Comment (rmja) [reply src/body_writer.rs]: I have renamed the function and it now returns `usize`.

**Review by bugadani — APPROVED** [review]
Thank you, I especially appreciate the myriad of added tests!
